### ISSUE TITLE
Questions about usage of pypose

### ISSUE THREAD

**Issue by MinJunKang** [pypose/tutorials#3]
Hello, thanks for sharing amazing work!

I am not sure this is the right place to ask, but I really want to ask some questions.

I am trying to optimize CNN features and camera poses together with this library which is similar to the task that [Back to the feature](https://github.com/cvg/pixloc) does.

In [Theseus library](https://github.com/facebookresearch/theseus), their method separates the learning parameters into optim_vars and aux_vars, and optimizes separately by using Inner optimization (LM optimizer) / outer optimization (Adam optimizer or others in PyTorch). In your examples, I can only find the LM optimizer that optimizes all the parameters together.

[1] How can I utilize multiple optimizers for learnable parameters with the pypose library?

[2] Is it possible to use multiple optimizers for the same parameter as well?

[3] Can you give any advice about using the pypose library to reimplement the model like https://github.com/cvg/pixloc/blob/master/pixloc/pixlib/geometry/optimization.py?

I really want your help to use this library.

**Comment by wang-chen** [comment]
Hi @MinJunKang, I am sorry for the late reply. We just noticed this issue.
A quick answer:
- For [1] and [2]. Yes, you may simply set the optimizer for different parameters/modules.
```python
net1 = Module1()
net2 = Module2()
optim1 = torch.optim.SGD(net1.parameters(), lr = 0.01)
optim2 = pp.optim.LM(net2) 
for ...:
    optim1.step()
    optim2.step()
```
If you want to use same parameters:
```python
net = Module()
optim1 = torch.optim.SGD(net.parameters(), lr = 0.01)
optim2 = pp.optim.LM(net) 
```
However, in the 2nd case, you need to be careful when you do optimization steps.

For [3], we will provide a more detailed tutorial in the next major release.

**Comment by MinJunKang** [comment]
Thanks for your help.

I am expecting your next major release, I think this library is so useful for further research and industry.

Thanks in advance!
